import {StyleSheet} from 'react-native';
import Colors from '../../utils/theme/colors';
import {dH, dW} from '../../utils/dynamicHeigthWidth';
import fonts from '../../assets/fonts';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.white,
    paddingHorizontal: dW(35),
  },
  SearchTextinputViewStyle: {
    marginTop: dH(40),
  },
  UpcomingViewStyle: {
    marginTop: dH(57),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  UpcomingTextStyle: {
    color: Colors.black,
    fontFamily: fonts.NexaBold,
    fontSize: dW(40),
    lineHeight: dH(52),
  },
  FilterIconStyle: {
    height: dH(46),
    width: dW(46),
    right: dW(20),
  },
  ActivityDataListViewStyle: {
    marginTop: dH(44),
    paddingVertical: dH(20),
  },
  ActivityCardViewStyle: {
    marginRight: dW(40),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 4,
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    width: dW(453),
    borderRadius: dW(30),
    backgroundColor: 'white',
  },
  ActivityImageStyle: {
    height: dH(239),
    width: dW(453),
    justifyContent: 'flex-end',
  },
  StarIconStyle: {
    height: dH(29),
    width: dW(28),
  },
  RatingTextStyle: {
    color: Colors.grey,
    fontFamily: fonts.NexaBold,
    fontSize: dW(32),
    left: dW(10),
  },
  LiniarEffectViewStyle: {
    flex: 1,
    justifyContent: 'flex-end',
    borderRadius: dW(30),
  },
  DetailViewStyle: {
    paddingHorizontal: dW(33),
  },
  ActivityTextStyle: {
    marginTop: dH(18),
    color: Colors.black,
    fontFamily: fonts.NexaBlack,
    fontSize: dW(24),
  },
  RatigViewStyle: {
    marginLeft: dW(20),
    flexDirection: 'row',
    alignItems: 'center',
  },
  LocationViewStyle: {
    marginTop: dH(20),
    flexDirection: 'row',
  },
  LocationIconStyle: {
    height: dH(30),
    width: dW(25),
  },
  LocationTextStyle: {
    left: dW(13),
    color: Colors.grey,
    fontFamily: fonts.NexaBook,
    fontSize: dW(19),
  },
  TimeDateTextStyle: {
    color: Colors.grey,
    fontSize: dW(25),
    fontFamily: fonts.NexaLigth,
    marginTop: dH(10),
  },
  TimeStyle: {
    color: Colors.grey,
    fontSize: dW(25),
    fontFamily: fonts.NexaLigth,
    marginBottom: dH(22),
  },
  DiscTextStyle: {
    color: Colors.dyGray,
    fontFamily: fonts.NexaBook,
    fontSize: dW(25),
    marginTop: dW(10),
  },
  PriceStyle: {
    color: Colors.black,
    fontFamily: fonts.NexaBold,
    fontSize: dW(25),
    marginTop: dW(10),
  },
  totalseattext: {
    color: Colors.dyGray,
    fontFamily: fonts.NexaBook,
    fontSize: dW(25),
    marginLeft: dW(10),
  },
  ReadMoreTextStyle: {
    color: Colors.lightBlue,
    fontFamily: fonts.NexaBook,
    fontSize: dW(18),
  },
  GroupIconStyle: {
    height: dH(52),
    width: dW(52),
  },
  SeatsViewStyle: {
    marginTop: dH(12),
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: dH(26),
  },
  GalleryTextStyle: {
    marginTop: dH(44),
    fontFamily: fonts.NexaBold,
    color: Colors.black,
    fontSize: dW(40),
  },
  GalleryImageStyle: {
    height: dH(156),
    width: dW(156),
    marginLeft: dW(18),
  },
  ParticipantTextStyle: {
    marginTop: dH(81),
    color: Colors.black,
    fontFamily: fonts.NexaBold,
    fontSize: dW(35),
  },
  CommonTotalViewStyle: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 4,
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    flex: 1,
    height: dH(120),
    borderRadius: dW(30),
    backgroundColor: 'white',
    marginHorizontal: dW(5),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: dW(33),
    marginTop: dH(40),
  },
  CommonFirstTextStyle: {
    color: Colors.black,
    fontFamily: fonts.NexaBold,
    fontSize: dW(35),
  },
  CommonSecoundTextStyle: {
    fontFamily: fonts.NexaBold,
    color: Colors.lightBlue,
    fontSize: dW(35),
  },
  CardViewStyle: {
    // height:dH(286),
    width: dW(553),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 4,
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    backgroundColor: 'white',
    borderRadius: dW(20),
    marginRight: dW(41),
    marginVertical: dH(10),
  },
  CardListViewStyle: {
    marginTop: dH(40),
  },
  ProfileHeaderViewStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: dW(25),
  },
  ProfileImageStyle: {
    height: dH(49),
    width: dW(49),
    borderRadius: dW(50),
  },
  ProfileViewStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: dH(29),
  },
  ProfileStarIconStyle: {
    height: dH(29),
    width: dW(29),
    right: dW(13),
  },
  UserNameStyle: {
    color: Colors.black,
    fontFamily: fonts.NexaBold,
    fontSize: dW(32),
    left: dW(10),
  },
  ratingTextStyle: {
    color: Colors.black,
    fontFamily: fonts.NexaBold,
  },
  TitleTextStyle: {
    marginTop: dH(17),
    color: Colors.black,
    fontFamily: fonts.NexaBook,
    paddingLeft: dW(25),
    paddingRight: dW(33),
    fontSize: dW(23),
  },
  discTextStyle: {
    paddingLeft: dW(25),
    paddingRight: dW(33),
    fontFamily: fonts.NexaBook,
    fontSize: dW(18),
    color: Colors.dyGray,
  },
  readMoreTextStyle: {
    color: Colors.lightBlue,
    fontSize: dW(18),
    fontFamily: fonts.NexaBook,
    paddingLeft: dW(25),
    paddingRight: dW(33),
  },
  HorizontalLineStyle: {
    height: 1,
    marginTop: dH(20),
    // flex:1,
    backgroundColor: Colors.dyGray,
  },
  FooterStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: dW(25),
  },
  likeSeactioViewStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: dH(16),
  },
  ComonLikeIconStyle: {
    height: dH(40),
    width: dW(42),
  },
  CommonLikeDislikeTextStyle: {
    color: Colors.inActive,
    fontSize: dW(18),
    fontFamily: fonts.NexaBold,
  },
  TimeTextStyle: {
    color: Colors.inActive,
    fontFamily: fonts.NexaBold,
    fontSize: dW(18),
  },
  MenuIconStyle: {
    height: dH(36),
    width: dW(36),
  },
  FeedTextStyle: {
    marginTop: dW(51),
    color: Colors.black,
    fontFamily: fonts.NexaBold,
    fontSize: dW(35),
  },
  SkillListViewStyle: {
    marginTop: dH(53),
  },
  SkillCardViewStyle: {
    borderColor: Colors.inActive,
    borderWidth: 1,
    borderRadius: dW(30),
    marginRight: dW(44),
  },
  IconViewStyle: {
    flex: 1,
    marginRight: dW(32),
    alignSelf: 'flex-end',
    justifyContent: 'space-between',
  },
  DotIConStyle: {
    top: dH(1),
    height: 49,
    width: dW(49),
  },
  HeartIconStyle: {
    top: dH(20),
    height: dH(49),
    width: dW(49),
  },
  SkillDetailViewStyle: {
    paddingHorizontal: dW(25),
    marginBottom: dH(15),
  },
  SkilNameTextStyle: {
    marginTop: dH(10),
    color: Colors.black,
    fontFamily: fonts.NexaBold,
    fontSize: dW(30),
  },
  timeTextStyle: {
    marginTop: dW(7),
    color: Colors.grey,
    fontFamily: fonts.NexaBook,
    fontSize: dW(21),
  },
  ProfileIconStyle: {
    height: dH(62),
    width: dW(62),
    borderRadius: dW(62),
  },
  SkillFooterViewStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  ProfileDetailStyle: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  nameTextStyle: {
    left: dW(15),
    color: Colors.grey,
    fontFamily: fonts.NexaBook,
    fontSize: dW(24),
  },
  RoundTextStyle: {
    color: Colors.grey,
    fontFamily: fonts.NexaBook,
    fontSize: dW(24),
  },
  participantTextStyle: {
    marginTop: dH(51),
    color: Colors.black,
    fontFamily: fonts.NexaBold,
    fontSize: dW(35),
  },
  ParticipantCardStyle: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 4,
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    backgroundColor: 'white',
    width: dW(255),
    borderRadius: dW(12),
    alignItems: 'center',
    marginRight: dW(31),
    marginVertical: dH(80),
  },
  ParticipantImageStyle: {
    height: dH(150),
    width: dW(150),
    borderColor: Colors.shadowColor,
    borderWidth: dW(3),
    borderRadius: dW(150),
    position: 'absolute',
    marginTop: dH(-75),
  },
  nameStyle: {
    marginTop: dH(100),
    color: Colors.black,
    fontFamily: fonts.NexaBold,
    fontSize: dW(25),
  },
  MusicStyle: {
    marginTop: dH(21),
    color: Colors.black,
    fontFamily: fonts.NexaBook,
    fontSize: dW(20),
  },
  MusicItemTextStyle: {
    fontFamily: fonts.NexaBold,
    color: Colors.black,
    fontSize: dW(20),
  },
  Participantstyle: {
    marginTop: dW(21),
    color: Colors.black,
    fontFamily: fonts.NexaBook,
    fontSize: dW(18),
    marginBottom: dH(24),
  },
  ParticipantNameItemStyle: {
    color: Colors.black,
    fontFamily: fonts.NexaBold,
    fontSize: dW(18),
  },
  ParticipantViewStyle: {
    marginTop: dH(52),
    marginBottom: dW(52),
  },
  RevenueViewStyle: {
    marginTop: dW(68),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  RevenueTextStyle: {
    color: Colors.black,
    fontFamily: fonts.NexaBold,
    fontSize: dW(35),
  },
});

export default styles;
