export const Strings = {
  welcome: {
    header: 'Welcome Back',
  },
  common: {
    emptyString: '',
    noData: 'No data found',
    success: 'success_type',
    failure: 'error_type',
    givePermissionSettings: 'One Percentage need permission from the settings.',
    allowCamera: 'Allow camera permission from settings',
    allowFile: 'Allow file permission from settings',
    givePermissionCamera: 'One Percentage need permission to camera',
    cancel: 'Cancel',
    ok: 'OK',
    chooseImage: 'Choose Image',
    selectOption: 'Please select any one option to select the image.',
    granted: 'granted',
    next: 'NEXT',
    rejected: 'rejected',
    somethingWrong: 'Something went wrong. Please try again.',
    back: 'Back',
    subscribe: 'SUBSCRIBE',
  },
  introPage: {
    welcome: 'WELCOME',
    subtitle:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  },
  Onboarding: {
    skip: 'SKIP',
    getstartted: "Let's Start",
  },
  otpVerify: {
    title: 'OTP Verification',
    subTitle: 'Enter 4 digits verification code we have sent to ',
  },
  signin: {
    setupAccount: 'Set up your account',
    subtitle: 'Sign in-up to enjoy the best managing experience',
    signin: 'Signin',
    signup: 'Signup',
    dontHaveAcc: "Don't have account?",
  },
  signup: {
    title: 'Signup',
    subTitle: 'Signup to enjoy the best managing experience',
  },
  search: {
    searchHere: 'Search here',
    suggestions: 'Suggestions',
    latestSearch: 'Latest search',
    search: 'Search',
    addToTrail: 'Add to trail',
  },
  verifyPhone: {
    verifyPhone: 'Verify Phone',
    codeIsSentTo: 'Code is sent to ',
    verify: 'Verify',
    errorCode: 'Please enter code',
    notYetCode: "Didn't receive OTP? ",
    resendNow: 'Resend Now',
    enterNumberOnly: 'Pleace enter number only',
  },
  walkThrough: {
    getStarted: 'Get Started',
  },
  searchResult: {
    searchResult: 'Search Result',
    trails: 'Trails',
    people: 'People',
    follow: '+Follow',
    unfollow: 'Unfollow',
  },
  pointsEarned: {
    description:
      'Hurray You Have Earned 1000 Tripster Credits For Successfully OnBoarding With Us',
  },
  interests: {
    title: 'Interest Mapping',
    description: 'Please select the Food Genre',
    continue: 'CONTINUE',
  },
  followersAndFollowing: {
    remove: 'Remove',
    following: 'Following',
    followers: 'Followers',
  },
  notifications: {
    title: 'Notification',
  },
  trendingDestinations: {
    trails: 'Trails',
  },
  trendingTrails: {
    title: 'Trendng Trails',
  },
  createTrips: {
    triptitle: 'Trip Title',
    tripDescription: 'Trip Description',
    interestCategory: 'Interest Category',
    selectCategory: 'Select Category',
    tripLocation: 'Trip Location',
    tripStartLocation: 'Start Location',
    tripEndLocation: 'End Location',
    tripView: 'Trip View',
    subscriptionCoin: 'Enter Subscription Coin',
  },

  restaurentCard: {
    totalPlatter: 'Total Platter',
    totalVisiter: 'TotalVisiter',
    AddBucket: 'ADD TO BUCKET',
    visit: 'VISIT',
  },
  createModal: {
    menu: 'MENU',
    recipe: 'RECIPE',
    post: 'POST',
  },
  createMenu: {
    headerTitle: 'Create Menu',
    title: 'Title',
    titlePlaceholder: 'Enter title',
    selectResturent: 'Select Resturent',
    selectResturentPlaceholder: 'Selectresturent',
    selctMenu: 'Select Food',
    subscriptionPoint: 'Subscription Point',
    enterPoint: 'Enter point',
    button: 'CREATE',
    coverPageTitle: 'Cover Photo',
    uploadCover: 'Upload Cover Photo',
  },
  menuCard: {
    totalFood: 'Total Food',
    subscribe: 'Subscribe',
    reviews: 'Reviews',
  },
  profile: {
    totalFoodToken: 'Total Food Tokens',
    totalPlatter: 'Total Platters Mode',
  },
  createPost: {
    headerTitle: 'Create Post',
    title: 'Title',
    titlePlaceholder: 'Enter title',
    interent: 'Choose Interest',
    menu: 'Select Menu',
    menuPlaceholder: 'Select Menu',
    media: 'Add Media',
    description: 'Description',
    button: 'NEXT',
    name: 'Name',
    namePlaceholder: 'Enter name',
    selected: 'Selected image/video',
    addLocation: 'Add location',
  },
  resturentDetail: {
    tableBook: 'Book a table',
    button: 'Pay Bill',
  },
};
